"""change to double

Revision ID: 0265d09edf20
Revises: fef8998aa482
Create Date: 2025-12-16 20:48:51.783148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0265d09edf20'
down_revision: Union[str, Sequence[str], None] = 'fef8998aa482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ptc_product_onec_id', 'product_tg_categories', ['product_onec_id'], unique=False)
    op.create_index('ix_ptc_tg_category_id', 'product_tg_categories', ['tg_category_id'], unique=False)
    op.alter_column('users', 'premium_requests',
               existing_type=sa.BIGINT(),
               type_=sa.Double(),
               existing_nullable=False,
               existing_server_default=sa.text('2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'premium_requests',
               existing_type=sa.Double(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text('2'))
    op.drop_index('ix_ptc_tg_category_id', table_name='product_tg_categories')
    op.drop_index('ix_ptc_product_onec_id', table_name='product_tg_categories')
    # ### end Alembic commands ###
