"""added premium until

Revision ID: 5710822b18aa
Revises: 3289bacafc2b
Create Date: 2025-12-17 23:10:14.664161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5710822b18aa'
down_revision: Union[str, Sequence[str], None] = '3289bacafc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('yandex_request_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'yandex_request_id')
    # ### end Alembic commands ###
