"""Init

Revision ID: 6a61c4029bd5
Revises: 
Create Date: 2025-10-22 14:46:10.971430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a61c4029bd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giveaways',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prize', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minimal_order_amount', sa.Numeric(precision=2), nullable=False),
    sa.Column('minimal_review_grade', sa.Integer(), nullable=False),
    sa.Column('minimal_review_length', sa.Integer(), nullable=False),
    sa.Column('minimal_referral_amount', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('onec_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onec_id')
    )
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('tg_ref_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('tg_phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tg_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=False)
    op.create_index(op.f('ix_users_tg_phone'), 'users', ['tg_phone'], unique=False)
    op.create_index(op.f('ix_users_tg_ref_id'), 'users', ['tg_ref_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('onec_id', sa.String(), nullable=False),
    sa.Column('unit_onec_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['unit_onec_id'], ['units.onec_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onec_id'),
    sa.UniqueConstraint('onec_id', 'unit_onec_id', name='uix_onec_unit')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('participants',
    sa.Column('giveaway_id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('completed_subscription', sa.Boolean(), nullable=False),
    sa.Column('completed_refs', sa.Boolean(), nullable=True),
    sa.Column('completed_deal', sa.Boolean(), nullable=True),
    sa.Column('deal_code', sa.BigInteger(), nullable=True),
    sa.Column('completed_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('giveaway_id', 'tg_id')
    )
    op.create_index(op.f('ix_participants_ref_id'), 'participants', ['ref_id'], unique=False)
    op.create_index(op.f('ix_participants_tg_id'), 'participants', ['tg_id'], unique=False)
    op.create_table('user_token_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('input_cost_usd', sa.Float(), nullable=True),
    sa.Column('output_cost_usd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_token_usage_date'), 'user_token_usage', ['date'], unique=False)
    op.create_index(op.f('ix_user_token_usage_user_id'), 'user_token_usage', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('onec_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('usage', sa.String(), nullable=True),
    sa.Column('expiration', sa.String(), nullable=True),
    sa.Column('category_onec_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_onec_id'], ['categories.onec_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'onec_id')
    )
    op.create_index(op.f('ix_products_category_onec_id'), 'products', ['category_onec_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_onec_id'), 'products', ['onec_id'], unique=True)
    op.create_table('features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('onec_id', sa.String(), nullable=False),
    sa.Column('product_onec_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_onec_id'], ['products.onec_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_code'), 'features', ['code'], unique=False)
    op.create_index(op.f('ix_features_file_id'), 'features', ['file_id'], unique=False)
    op.create_index(op.f('ix_features_id'), 'features', ['id'], unique=False)
    op.create_index(op.f('ix_features_name'), 'features', ['name'], unique=False)
    op.create_index(op.f('ix_features_onec_id'), 'features', ['onec_id'], unique=True)
    op.create_index(op.f('ix_features_product_onec_id'), 'features', ['product_onec_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_features_product_onec_id'), table_name='features')
    op.drop_index(op.f('ix_features_onec_id'), table_name='features')
    op.drop_index(op.f('ix_features_name'), table_name='features')
    op.drop_index(op.f('ix_features_id'), table_name='features')
    op.drop_index(op.f('ix_features_file_id'), table_name='features')
    op.drop_index(op.f('ix_features_code'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_products_onec_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_onec_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_user_token_usage_user_id'), table_name='user_token_usage')
    op.drop_index(op.f('ix_user_token_usage_date'), table_name='user_token_usage')
    op.drop_table('user_token_usage')
    op.drop_index(op.f('ix_participants_tg_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_ref_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_tg_ref_id'), table_name='users')
    op.drop_index(op.f('ix_users_tg_phone'), table_name='users')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_table('units')
    op.drop_table('giveaways')
    # ### end Alembic commands ###
