"""baseline

Revision ID: 7c65cd5f9a4a
Revises: 
Create Date: 2025-11-19 21:33:18.712439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c65cd5f9a4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bags_id'), 'bags', ['id'], unique=False)
    op.create_index(op.f('ix_bags_tg_id'), 'bags', ['tg_id'], unique=False)
    op.create_table('bag_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bag_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bag_id'], ['bags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bag_items_bag_id'), 'bag_items', ['bag_id'], unique=False)
    op.create_index(op.f('ix_bag_items_id'), 'bag_items', ['id'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('bag_id', sa.BigInteger(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bag_id'], ['bags.id'], ),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_bag_id'), 'carts', ['bag_id'], unique=False)
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_index(op.f('ix_carts_last_updated'), 'carts', ['last_updated'], unique=False)
    op.create_index(op.f('ix_carts_tg_id'), 'carts', ['tg_id'], unique=False)
    op.alter_column('giveaways', 'minimal_order_amount',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('users', 'tg_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('giveaways', 'minimal_order_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    op.drop_index(op.f('ix_carts_tg_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_last_updated'), table_name='carts')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_bag_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_bag_items_id'), table_name='bag_items')
    op.drop_index(op.f('ix_bag_items_bag_id'), table_name='bag_items')
    op.drop_table('bag_items')
    op.drop_index(op.f('ix_bags_tg_id'), table_name='bags')
    op.drop_index(op.f('ix_bags_id'), table_name='bags')
    op.drop_table('bags')
    # ### end Alembic commands ###
