"""adding tg categories

Revision ID: bb2251f3cc81
Revises: 3fb5ec99b0c4
Create Date: 2025-12-16 17:21:53.989404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2251f3cc81'
down_revision: Union[str, Sequence[str], None] = '3fb5ec99b0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_categories_created_at'), 'tg_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_tg_categories_name'), 'tg_categories', ['name'], unique=True)
    op.create_index(op.f('ix_tg_categories_updated_at'), 'tg_categories', ['updated_at'], unique=False)
    op.create_table('product_tg_categories',
    sa.Column('product_onec_id', sa.String(), nullable=False),
    sa.Column('tg_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_onec_id'], ['products.onec_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tg_category_id'], ['tg_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_onec_id', 'tg_category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_tg_categories')
    op.drop_index(op.f('ix_tg_categories_updated_at'), table_name='tg_categories')
    op.drop_index(op.f('ix_tg_categories_name'), table_name='tg_categories')
    op.drop_index(op.f('ix_tg_categories_created_at'), table_name='tg_categories')
    op.drop_table('tg_categories')
    # ### end Alembic commands ###
