"""added promo_discount_pct

Revision ID: d878ab301493
Revises: e325df90d2cc
Create Date: 2025-12-20 18:33:34.342317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd878ab301493'
down_revision: Union[str, Sequence[str], None] = 'e325df90d2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_codes', sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_codes', 'discount_pct')
    # ### end Alembic commands ###
