"""added promo_gains

Revision ID: fbd8b39a868e
Revises: d878ab301493
Create Date: 2025-12-21 18:10:04.739701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd8b39a868e'
down_revision: Union[str, Sequence[str], None] = 'd878ab301493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('promo_gains_given', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'promo_gains_given')
    # ### end Alembic commands ###
